"""
Export utilities for liver vascular networks.
"""

import json
from pathlib import Path
from typing import Tuple
from .tree import VascularTree
from .config import LiverVascularConfig


def export_to_python_module(
    arterial_tree: VascularTree,
    venous_tree: VascularTree,
    config: LiverVascularConfig,
    output_path: Path,
) -> None:
    """
    Export vascular network to a Python module file.
    
    The generated module contains:
    - NODES: List of node dictionaries
    - SEGMENTS: List of segment dictionaries
    - ROOTS: Dictionary with arterial and venous root IDs
    - CONFIG: Configuration used for generation
    
    Parameters
    ----------
    arterial_tree : VascularTree
        Arterial tree
    venous_tree : VascularTree
        Venous tree
    config : LiverVascularConfig
        Configuration used
    output_path : Path
        Path to output .py file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    all_nodes = []
    all_segments = []
    
    arterial_offset = 0
    for node in arterial_tree.nodes:
        node_dict = node.to_dict()
        node_dict["tree_type"] = "arterial"
        all_nodes.append(node_dict)
    
    for segment in arterial_tree.segments:
        seg_dict = segment.to_dict()
        seg_dict["tree_type"] = "arterial"
        all_segments.append(seg_dict)
    
    venous_offset = len(arterial_tree.nodes)
    for node in venous_tree.nodes:
        node_dict = node.to_dict()
        node_dict["id"] += venous_offset
        if node_dict["parent_id"] is not None:
            node_dict["parent_id"] += venous_offset
        node_dict["children_ids"] = [cid + venous_offset for cid in node_dict["children_ids"]]
        node_dict["tree_type"] = "venous"
        all_nodes.append(node_dict)
    
    for segment in venous_tree.segments:
        seg_dict = segment.to_dict()
        seg_dict["id"] += len(arterial_tree.segments)
        seg_dict["parent_node_id"] += venous_offset
        seg_dict["child_node_id"] += venous_offset
        seg_dict["tree_type"] = "venous"
        all_segments.append(seg_dict)
    
    with open(output_path, "w") as f:
        f.write('"""\n')
        f.write("Liver vascular network generated by generators.liver\n")
        f.write(f"Random seed: {config.random_seed}\n")
        f.write(f"Schema version: {config.schema_version}\n")
        f.write('"""\n\n')
        
        f.write("import numpy as np\n\n")
        
        f.write("# Configuration\n")
        f.write(f"CONFIG = {repr(config.to_dict())}\n\n")
        
        f.write("# Nodes\n")
        f.write(f"NODES = {repr(all_nodes)}\n\n")
        
        f.write("# Segments\n")
        f.write(f"SEGMENTS = {repr(all_segments)}\n\n")
        
        f.write("# Root node IDs\n")
        f.write(f"ROOTS = {{\n")
        f.write(f'    "arterial": {arterial_offset},\n')
        f.write(f'    "venous": {venous_offset},\n')
        f.write(f"}}\n\n")
        
        f.write("def get_nodes_by_tree(tree_type):\n")
        f.write('    """Get all nodes for a specific tree type."""\n')
        f.write('    return [n for n in NODES if n["tree_type"] == tree_type]\n\n')
        
        f.write("def get_segments_by_tree(tree_type):\n")
        f.write('    """Get all segments for a specific tree type."""\n')
        f.write('    return [s for s in SEGMENTS if s["tree_type"] == tree_type]\n')
    
    print(f"Exported Python module to {output_path}")


def export_to_json(
    arterial_tree: VascularTree,
    venous_tree: VascularTree,
    config: LiverVascularConfig,
    output_path: Path,
) -> None:
    """
    Export vascular network to JSON file.
    
    Parameters
    ----------
    arterial_tree : VascularTree
        Arterial tree
    venous_tree : VascularTree
        Venous tree
    config : LiverVascularConfig
        Configuration used
    output_path : Path
        Path to output .json file
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    data = {
        "schema_version": config.schema_version,
        "config": config.to_dict(),
        "arterial_tree": arterial_tree.to_dict(),
        "venous_tree": venous_tree.to_dict(),
        "statistics": {
            "arterial_nodes": len(arterial_tree.nodes),
            "arterial_segments": len(arterial_tree.segments),
            "venous_nodes": len(venous_tree.nodes),
            "venous_segments": len(venous_tree.segments),
        },
    }
    
    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)
    
    print(f"Exported JSON to {output_path}")
